sudo: required
language: php
services:
- docker

env:
  matrix:
    secure: hiSFSYq9bzBV4EZffJHfMPpH2R7j7buWNx3h9SyxRkiwCYzBPQV3mKnFTURasweGOYq5XlRCE2wUIQwGxoi8yUCLLroXLzS4x7DP08cQK0Gc79DSmEkArn8ftP4IMXtkYiv81pAWDt4u4XXYROh8epQmYmTqewR1bSgzoRsp6p83Pq9NgwEzCYfhf1GKy9zkrIrXqlMmr11cw0o0LOOOYLsqnscEClzlY2A1oYPRgFq/yWDe69yWNGA48WXrUwXFSqURajJwLU01NlRlL5s3x3SjVCz379HufWoKl5OnHbPl+9a5MNv6kW2JWlrUDkWAttn1vTJfOVVsPofBBRcuYpCdhYrUvggR341hXiBQt8+1HuZbSZ5nN9WEjqL25fM0iKWqE1yi9Nf9oM9QiplgQVZA8u/AoTSO+nJ2I4iE12GF72rWY7Wamv0kC+BeXnpSK99DBw9RuWEg/S0NkdWlgA16k7MrEhLp76tzhCuUNMrCRveoh87S5qWfhzRmcyHo+eBQCXzo+1Gzy4Evzu3YAwgKt3ZybzBjCCv9uKizwSt5Cbg/Qqd0ed0MNrhmOLKkJlzeQMR2Tpse6cpGtlThZpe1ngfgBxFbKjxmIOpwJYEUrX/AM00cmuYmZvi0wLnLolu83NOu3AL32kv4ZODCQpaHMSgflV/zwve0JpUyhX8=

cache:
  directories:
  - "$HOME/.composer/cache/files"

addons:
  ssh_known_hosts:
  - "$STAGING_DEPLOY_HOST"
  - "$PRODUCTION_DEPLOY_HOST"

before_script:
- echo -e "Host $STAGING_DEPLOY_HOST StrictHostKeyChecking no" >> ~/.ssh/config
- echo -e "Host $PRODUCTION_DEPLOY_HOST StrictHostKeyChecking no" >> ~/.ssh/config
- echo -e "UserKnownHostsFile /dev/null" >> ~/.ssh/config

script:
- mkdir vendor
- touch vendor/test

before_deploy:
- openssl aes-256-cbc -K $encrypted_e48376434120_key -iv $encrypted_e48376434120_iv -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
- provider: script
  skip_cleanup: true
  script: "{./.travis/deploy.sh} 2>&1 > /dev/null"
  on:
    branch: 
    - develop
    - master

notifications:
  slack: diolinuxmediagroup:u7wue4EXRNFq71hhlobDCVZf
